project:
  type: website
  output-dir: docs

website:
  title: "Anxo Sánchez"
  twitter-card: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - listing.qmd

format:
  html:
    theme: 
      light: morph
      dark: solar
    #mainfont: arial
    #fontsize: 1.5em
    #fontcolor: "#0013d5"
    #linkcolor: "#ff33f0"
    #monofont: courier new
    css: styles.css
    toc: true



