project:
  type: website
  output-dir: docs

website:
  title: "Anxo Sánchez"
  favicon: anxoblogiconlogo.bmp
  twitter-card:
    creator: "@dragsonstyle"
    site: "@rstudio"
  site-url: https://anxosanchez.github.io/anxoblog/
  cookie-consent: false
  page-footer: 
    left: "Copyright 2023, Anxo Sánchez"
    right:
      - icon: github
        href: https://github.com/anxosanchez
      - icon: twitter
        href: https://twitter.com/anxosanchez
      - icon: linkedin
        href: https://www.linkedin.com/in/anxo-s%C3%A1nchez-berm%C3%BAdez-79086321/  
  #body-header: | 
  #  This page brought to you by <https://example.com>
  #margin-header: |
  #  ![Logo image](/img/logo.png)
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Asignaturas
        menu:
          - EQI1.qmd
          - EQI2.qmd
          - SOPQ.qmd
          - IQMPP.qmd
    right:
      - href: listing.qmd
        text: Blog

format:
  html:
    theme: 
      light: morph
      dark: solar
    #mainfont: arial
    #fontsize: 1.5em
    #fontcolor: "#0013d5"
    #linkcolor: "#ff33f0"
    #monofont: courier new
    css: styles.css
    toc: true



